type Product = [string, string, string];

const groups = [
  ['Obst & Gemüse', ['Apfel','Birne','Banane','Orange','Mandarine','Zitrone','Limette','Trauben','Erdbeeren','Heidelbeeren','Himbeeren','Kirschen','Pfirsich','Nektarine','Pflaumen','Kiwi','Mango','Ananas','Avocado','Tomaten'], ['frisch','Bio','regional','Snackgröße','Familienpackung'], '500 g'],
  ['Gemüse & Salat', ['Gurke','Paprika','Karotten','Kartoffeln','Zwiebeln','Knoblauch','Brokkoli','Blumenkohl','Zucchini','Aubergine','Champignons','Spinat','Lauch','Sellerie','Radieschen','Feldsalat','Kopfsalat','Rucola','Kohlrabi','Süßkartoffeln'], ['frisch','Bio','regional','küchenfertig','Familienpackung'], '500 g'],
  ['Molkerei & Kühlung', ['Milch','Joghurt','Quark','Butter','Margarine','Sahne','Schmand','Crème fraîche','Frischkäse','Gouda','Emmentaler','Mozzarella','Feta','Parmesan','Eier','Pudding','Kefir','Buttermilch','Haferdrink','Sojadrink'], ['Natur','fettarm','laktosefrei','Bio','Großpackung'], '1 Packung'],
  ['Backwaren', ['Brot','Vollkornbrot','Toastbrot','Brötchen','Baguette','Ciabatta','Knäckebrot','Wraps','Croissants','Laugengebäck','Rosinenbrot','Pumpernickel','Fladenbrot','Burgerbrötchen','Hotdog-Brötchen'], ['klassisch','Vollkorn','Bio','glutenfrei','Familienpackung'], '1 Packung'],
  ['Vorrat', ['Nudeln','Spaghetti','Reis','Couscous','Bulgur','Haferflocken','Müsli','Cornflakes','Mehl','Zucker','Linsen','Kichererbsen','Kidneybohnen','Mais','Passierte Tomaten','Tomatenmark','Pesto','Kartoffelpüree','Gemüsebrühe','Kokosmilch'], ['klassisch','Bio','Vollkorn','fein','Großpackung'], '500 g'],
  ['Fleisch & Fisch', ['Hackfleisch','Rindersteak','Schweineschnitzel','Hähnchenbrust','Hähnchenschenkel','Putenbrust','Bratwurst','Wiener Würstchen','Salami','Kochschinken','Lachsfilet','Seelachsfilet','Garnelen','Thunfisch','Fischstäbchen'], ['frisch','Bio','mariniert','familienpackung','tiefgekühlt'], '500 g'],
  ['Tiefkühlkost', ['Pizza Margherita','Pizza Salami','Pommes frites','Kroketten','Gemüsemischung','Erbsen','Spinat','Beerenmischung','Eiscreme','Lasagne','Hähnchen-Nuggets','Frühlingsrollen','Kräuter','Brötchen','Kartoffeltaschen'], ['klassisch','Bio','XXL','vegetarisch','Familienpackung'], '1 Packung'],
  ['Getränke', ['Mineralwasser','Apfelsaft','Orangensaft','Multivitaminsaft','Cola','Limonade','Eistee','Kaffee','Espresso','Schwarztee','Grüntee','Kräutertee','Kakao','Malzgetränk','Tonic Water'], ['klassisch','zuckerfrei','Bio','Mehrweg','Familienpackung'], '1 l'],
  ['Süßes & Snacks', ['Schokolade','Gummibärchen','Kekse','Waffeln','Chips','Salzstangen','Nüsse','Popcorn','Müsliriegel','Fruchtgummi','Pralinen','Cracker','Reiswaffeln','Studentenfutter','Erdnüsse'], ['klassisch','Vollmilch','zuckerreduziert','Bio','Großpackung'], '1 Packung'],
  ['Haushalt', ['Toilettenpapier','Küchenrolle','Spülmittel','Spülmaschinentabs','Waschmittel','Weichspüler','Müllbeutel','Allzweckreiniger','Glasreiniger','Badreiniger','Schwämme','Backpapier','Alufolie','Frischhaltefolie','Gefrierbeutel'], ['klassisch','sensitiv','ökologisch','Nachfüllpack','Vorratspack'], '1 Packung'],
  ['Drogerie', ['Zahnpasta','Zahnbürsten','Duschgel','Shampoo','Spülung','Seife','Deodorant','Handcreme','Bodylotion','Taschentücher','Wattepads','Rasiergel','Rasierklingen','Sonnencreme','Pflaster'], ['klassisch','sensitiv','für Kinder','Naturkosmetik','Vorratspack'], '1 Packung'],
  ['Baby & Tierbedarf', ['Windeln','Feuchttücher','Babynahrung','Babybrei','Babyshampoo','Katzenfutter nass','Katzenfutter trocken','Katzenstreu','Hundefutter nass','Hundefutter trocken','Hundesnacks','Vogelfutter','Kleintierstreu','Tier-Spielzeug','Kotbeutel'], ['klassisch','sensitiv','Bio','Junior','Vorratspack'], '1 Packung'],
] as const;

const hygieneProducts: Product[] = [
  ['Mundspülung', 'Drogerie', '500 ml'],
  ['Zahnseide', 'Drogerie', '1 Packung'],
  ['Interdentalbürsten', 'Drogerie', '1 Packung'],
  ['Zungenreiniger', 'Drogerie', '1 Stück'],
  ['Zahnbürstenköpfe', 'Drogerie', '1 Packung'],
  ['Kinderzahnpasta', 'Drogerie', '1 Tube'],
  ['Flüssigseife', 'Drogerie', '1 Flasche'],
  ['Handseife Nachfüllpack', 'Drogerie', '1 Packung'],
  ['Duschcreme', 'Drogerie', '1 Flasche'],
  ['Duschöl', 'Drogerie', '1 Flasche'],
  ['Intimwaschlotion', 'Drogerie', '1 Flasche'],
  ['Trockenshampoo', 'Drogerie', '1 Dose'],
  ['Haarspülung', 'Drogerie', '1 Flasche'],
  ['Haarkur', 'Drogerie', '1 Packung'],
  ['Haarbürste', 'Drogerie', '1 Stück'],
  ['Kamm', 'Drogerie', '1 Stück'],
  ['Haargummis', 'Drogerie', '1 Packung'],
  ['Deospray', 'Drogerie', '1 Dose'],
  ['Deoroller', 'Drogerie', '1 Stück'],
  ['Gesichtsreinigung', 'Drogerie', '1 Flasche'],
  ['Gesichtswasser', 'Drogerie', '1 Flasche'],
  ['Gesichtscreme', 'Drogerie', '1 Tiegel'],
  ['Augencreme', 'Drogerie', '1 Tube'],
  ['Lippenpflege', 'Drogerie', '1 Stück'],
  ['Abschminktücher', 'Drogerie', '1 Packung'],
  ['Mizellenwasser', 'Drogerie', '400 ml'],
  ['Wattestäbchen', 'Drogerie', '1 Packung'],
  ['Kosmetiktücher', 'Drogerie', '1 Box'],
  ['Feuchtes Toilettenpapier', 'Drogerie', '1 Packung'],
  ['Waschlappen', 'Drogerie', '1 Stück'],
  ['Rasierschaum', 'Drogerie', '1 Dose'],
  ['Einwegrasierer', 'Drogerie', '1 Packung'],
  ['Aftershave', 'Drogerie', '1 Flasche'],
  ['Bartshampoo', 'Drogerie', '1 Flasche'],
  ['Bartöl', 'Drogerie', '1 Flasche'],
  ['Nagelschere', 'Drogerie', '1 Stück'],
  ['Nagelfeile', 'Drogerie', '1 Stück'],
  ['Nagelknipser', 'Drogerie', '1 Stück'],
  ['Handdesinfektionsmittel', 'Drogerie', '1 Flasche'],
  ['Desinfektionstücher', 'Drogerie', '1 Packung'],
  ['Wunddesinfektion', 'Drogerie', '1 Flasche'],
  ['Wundpflaster', 'Drogerie', '1 Packung'],
  ['Blasenpflaster', 'Drogerie', '1 Packung'],
  ['Mullbinden', 'Drogerie', '1 Packung'],
  ['Damenbinden', 'Drogerie', '1 Packung'],
  ['Tampons', 'Drogerie', '1 Packung'],
  ['Slipeinlagen', 'Drogerie', '1 Packung'],
  ['Menstruationstasse', 'Drogerie', '1 Stück'],
  ['Inkontinenzeinlagen', 'Drogerie', '1 Packung'],
  ['Kondome', 'Drogerie', '1 Packung'],
  ['Kontaktlinsenlösung', 'Drogerie', '1 Flasche'],
  ['Kontaktlinsenbehälter', 'Drogerie', '1 Stück'],
  ['Ohrenstöpsel', 'Drogerie', '1 Packung'],
  ['Sonnencreme Gesicht', 'Drogerie', '1 Tube'],
  ['Sonnencreme Kinder', 'Drogerie', '1 Flasche'],
  ['After-Sun-Lotion', 'Drogerie', '1 Flasche'],
  ['Insektenschutzspray', 'Drogerie', '1 Flasche'],
  ['Fußcreme', 'Drogerie', '1 Tube'],
  ['Hornhautfeile', 'Drogerie', '1 Stück'],
  ['Badezusatz', 'Drogerie', '1 Packung'],
  ['Badesalz', 'Drogerie', '1 Packung'],
  ['Bademantel', 'Drogerie', '1 Stück'],
  ['Mikrofaser-Handtuch', 'Drogerie', '1 Stück'],
  ['Reise-Hygieneset', 'Drogerie', '1 Set'],
  ['Hygienebeutel', 'Drogerie', '1 Packung'],
  ['Einmalhandschuhe', 'Drogerie', '1 Packung'],
  ['FFP2-Masken', 'Drogerie', '1 Packung'],
  ['Fieberthermometer', 'Drogerie', '1 Stück'],
  ['Läusekamm', 'Drogerie', '1 Stück'],
  ['Läuseshampoo', 'Drogerie', '1 Flasche'],
];

const additionalProductGroups = [
  ['Obst & Gemüse', '500 g', ['Aprikosen','Granatapfel','Grapefruit','Pomelo','Wassermelone','Honigmelone','Cantaloupe-Melone','Passionsfrucht','Maracuja','Papaya','Guave','Litschi','Kaki','Feigen','Datteln frisch','Johannisbeeren','Stachelbeeren','Brombeeren','Cranberrys','Holunderbeeren','Mirabellen','Quitten','Rhabarber','Kumquats','Physalis','Nashi-Birnen','Sternfrucht','Drachenfrucht','Kokosnuss','Kochbananen','Artischocken','Fenchel','Pak Choi','Mangold','Grünkohl','Wirsing','Rotkohl','Weißkohl','Spitzkohl','Rosenkohl','Chicorée','Endiviensalat','Eisbergsalat','Romanasalat','Frühlingszwiebeln','Schalotten','Pastinaken','Petersilienwurzel','Rote Bete','Steckrüben','Topinambur','Maiskolben','Okraschoten','Zuckerschoten','Grüne Bohnen','Dicke Bohnen','Kürbis Hokkaido','Butternut-Kürbis','Spargel grün','Spargel weiß']],
  ['Nudeln & Pasta', '500 g', ['Penne Rigate','Fusilli','Farfalle','Rigatoni','Tortiglioni','Maccheroni','Makkaroni','Linguine','Tagliatelle','Fettuccine','Pappardelle','Capellini','Bucatini','Vermicelli','Orecchiette','Conchiglie','Gnocchetti Sardi','Casarecce','Cavatappi','Radiatori','Ditalini','Risoni','Lasagneplatten','Cannelloni','Tortellini Käse','Tortellini Fleisch','Ravioli Ricotta-Spinat','Ravioli Fleisch','Spätzle','Knöpfle','Schupfnudeln','Maultaschen','Eiernudeln','Bandnudeln','Suppennudeln','Fadennudeln','Buchstabennudeln','Glasnudeln','Reisnudeln','Mie-Nudeln','Udon-Nudeln','Soba-Nudeln','Ramen-Nudeln','Vollkornspaghetti','Dinkelpasta','Linsennudeln','Kichererbsennudeln','Erbsennudeln','Maisnudeln','Glutenfreie Nudeln']],
  ['Sättigungsbeilagen', '500 g', ['Basmatireis','Jasminreis','Langkornreis','Rundkornreis','Risottoreis Arborio','Risottoreis Carnaroli','Milchreis','Wildreis','Naturreis','Vollkornreis','Parboiled Reis','Sushireis','Quinoa weiß','Quinoa rot','Quinoa tricolor','Hirse','Polenta','Buchweizen','Graupen','Perlgraupen','Amaranth','Dinkelreis','Ebly Zartweizen','Kartoffelknödel','Semmelknödel','Serviettenknödel','Gnocchi','Kartoffelpuffer','Rösti','Kartoffelgratin','Kartoffelecken','Süßkartoffelpommes','Kartoffelkroketten','Stampfkartoffeln','Couscous Vollkorn','Perlcouscous','Bulgur fein','Bulgur grob','Falafel-Mix','Baguette zum Aufbacken']],
  ['Fleisch & Geflügel', '500 g', ['Rinderhackfleisch','Gemischtes Hackfleisch','Schweinehackfleisch','Kalbshackfleisch','Rinderfilet','Rumpsteak','Entrecôte','Roastbeef','Rindergulasch','Rinderrouladen','Suppenfleisch','Tafelspitz','Kalbsschnitzel','Kalbsgulasch','Kalbsleber','Schweinefilet','Schweinekotelett','Schweinebauch','Schweinebraten','Schweinegulasch','Nackensteak','Kasseler','Spareribs','Lammfilet','Lammkotelett','Lammkeule','Lammhackfleisch','Wildgulasch','Rehkeule','Hirschsteak','Kaninchen','Hähnchen ganz','Hähnchenflügel','Hähnchenoberkeulen','Hähncheninnenfilet','Putensteak','Putenschnitzel','Entenbrust','Ente ganz','Gänsebrust','Gans ganz','Hähnchenleber','Rinderleber','Bacon','Frühstücksspeck','Chorizo','Mettenden','Leberkäse','Cevapcici','Frikadellen']],
  ['Grillen', '1 Packung', ['Grillbratwurst','Thüringer Rostbratwurst','Nürnberger Rostbratwürste','Krakauer','Käsekrainer','Merguez','Geflügelbratwurst','Vegane Grillwurst','Rinderhüftsteak mariniert','Schweinenacken mariniert','Holzfällersteak','Bauchscheiben mariniert','Spareribs mariniert','Hähnchenspieße','Putenspieße','Schaschlikspieße','Hackfleischspieße','Lammspieße','Grillfackeln','Burger Patties Rind','Burger Patties vegetarisch','Halloumi','Grillkäse','Feta zum Grillen','Maiskolben vorgekocht','Grillgemüse-Mix','Gefüllte Champignons','Folienkartoffeln','Kräuterbutter','Knoblauchbutter','Grillsauce BBQ','Steaksauce','Currysauce','Cocktailsauce','Knoblauchsauce','Chilisauce','Tzatziki','Senf mittelscharf','Ketchup','Mayonnaise','Burgerbrötchen Brioche','Hotdog-Brötchen','Baguette Kräuter','Kartoffelsalat','Nudelsalat','Krautsalat','Grillkohle','Grillbriketts','Anzündwürfel','Grillschalen','Grillspieße Holz','Aluminium-Grillfolie','Grillhandschuhe','Grillbürste','Räucherchips']],
  ['Backen & Kochen', '1 Packung', ['Weizenmehl Type 405','Weizenmehl Type 550','Weizenmehl Type 1050','Dinkelmehl Type 630','Dinkelmehl Type 1050','Roggenmehl Type 1150','Vollkornmehl','Pizzamehl Type 00','Speisestärke','Kartoffelstärke','Maisstärke','Paniermehl','Panko','Semmelbrösel','Trockenhefe','Frische Hefe','Natron','Weinsteinbackpulver','Vanillezucker','Bourbon-Vanillezucker','Puderzucker','Brauner Zucker','Rohrzucker','Gelierzucker 1:1','Gelierzucker 2:1','Gelierzucker 3:1','Kuvertüre Zartbitter','Kuvertüre Vollmilch','Kuvertüre weiß','Backkakao','Schokotropfen','Kokosraspeln','Gemahlene Mandeln','Gehackte Mandeln','Gemahlene Haselnüsse','Rosinen','Orangeat','Zitronat','Marzipanrohmasse','Tortenguss klar','Tortenguss rot','Sahnesteif','Gelatine gemahlen','Gelatineblätter','Agar-Agar','Puddingpulver Vanille','Puddingpulver Schokolade','Vanilleextrakt','Rum-Aroma','Bittermandel-Aroma','Zitronen-Aroma','Lebensmittelfarbe','Zuckerstreusel','Muffinförmchen','Backpapier Zuschnitte','Bratschlauch','Röstzwiebeln','Sojasauce','Worcestersauce','Balsamico-Essig','Apfelessig','Weißweinessig','Rotweinessig','Sesamöl','Rapsöl','Sonnenblumenöl','Erdnussöl','Butterschmalz','Kochsahne','Bratenfond','Rinderfond','Geflügelfond','Gemüsefond','Tomatensauce','Currypaste rot','Currypaste grün','Tahini','Erdnussbutter','Kapern','Oliven','Getrocknete Tomaten','Sambal Oelek','Meerrettich','Gewürzgurken','Senfkörner','Lorbeerblätter','Muskatnuss','Paprikapulver edelsüß','Paprikapulver geräuchert','Currypulver','Kreuzkümmel','Kurkuma','Zimt','Oregano','Thymian','Rosmarin','Basilikum getrocknet','Chiliflocken']],
] as const;

const additionalProducts: Product[] = additionalProductGroups.flatMap(([category, quantity, names]) =>
  names.map((name) => [name, category, quantity] as Product),
);

export const extendedCatalog: Product[] = [
  ...groups.flatMap(([category, bases, variants, quantity]) =>
    bases.flatMap((base) => variants.map((variant) => [`${base} – ${variant}`, category, quantity] as Product)),
  ).slice(0, 850),
  ...hygieneProducts,
  ...additionalProducts,
];
