type Product = [string, string, string];

const groups = [
  ['Obst & Gemüse', ['Apfel','Birne','Banane','Orange','Mandarine','Zitrone','Limette','Trauben','Erdbeeren','Heidelbeeren','Himbeeren','Kirschen','Pfirsich','Nektarine','Pflaumen','Kiwi','Mango','Ananas','Avocado','Tomaten'], ['frisch','Bio','regional','Snackgröße','Familienpackung'], '500 g'],
  ['Gemüse & Salat', ['Gurke','Paprika','Karotten','Kartoffeln','Zwiebeln','Knoblauch','Brokkoli','Blumenkohl','Zucchini','Aubergine','Champignons','Spinat','Lauch','Sellerie','Radieschen','Feldsalat','Kopfsalat','Rucola','Kohlrabi','Süßkartoffeln'], ['frisch','Bio','regional','küchenfertig','Familienpackung'], '500 g'],
  ['Molkerei & Kühlung', ['Milch','Joghurt','Quark','Butter','Margarine','Sahne','Schmand','Crème fraîche','Frischkäse','Gouda','Emmentaler','Mozzarella','Feta','Parmesan','Eier','Pudding','Kefir','Buttermilch','Haferdrink','Sojadrink'], ['Natur','fettarm','laktosefrei','Bio','Großpackung'], '1 Packung'],
  ['Backwaren', ['Brot','Vollkornbrot','Toastbrot','Brötchen','Baguette','Ciabatta','Knäckebrot','Wraps','Croissants','Laugengebäck','Rosinenbrot','Pumpernickel','Fladenbrot','Burgerbrötchen','Hotdog-Brötchen'], ['klassisch','Vollkorn','Bio','glutenfrei','Familienpackung'], '1 Packung'],
  ['Vorrat', ['Nudeln','Spaghetti','Reis','Couscous','Bulgur','Haferflocken','Müsli','Cornflakes','Mehl','Zucker','Linsen','Kichererbsen','Kidneybohnen','Mais','Passierte Tomaten','Tomatenmark','Pesto','Kartoffelpüree','Gemüsebrühe','Kokosmilch'], ['klassisch','Bio','Vollkorn','fein','Großpackung'], '500 g'],
  ['Fleisch & Fisch', ['Hackfleisch','Rindersteak','Schweineschnitzel','Hähnchenbrust','Hähnchenschenkel','Putenbrust','Bratwurst','Wiener Würstchen','Salami','Kochschinken','Lachsfilet','Seelachsfilet','Garnelen','Thunfisch','Fischstäbchen'], ['frisch','Bio','mariniert','familienpackung','tiefgekühlt'], '500 g'],
  ['Tiefkühlkost', ['Pizza Margherita','Pizza Salami','Pommes frites','Kroketten','Gemüsemischung','Erbsen','Spinat','Beerenmischung','Eiscreme','Lasagne','Hähnchen-Nuggets','Frühlingsrollen','Kräuter','Brötchen','Kartoffeltaschen'], ['klassisch','Bio','XXL','vegetarisch','Familienpackung'], '1 Packung'],
  ['Getränke', ['Mineralwasser','Apfelsaft','Orangensaft','Multivitaminsaft','Cola','Limonade','Eistee','Kaffee','Espresso','Schwarztee','Grüntee','Kräutertee','Kakao','Malzgetränk','Tonic Water'], ['klassisch','zuckerfrei','Bio','Mehrweg','Familienpackung'], '1 l'],
  ['Süßes & Snacks', ['Schokolade','Gummibärchen','Kekse','Waffeln','Chips','Salzstangen','Nüsse','Popcorn','Müsliriegel','Fruchtgummi','Pralinen','Cracker','Reiswaffeln','Studentenfutter','Erdnüsse'], ['klassisch','Vollmilch','zuckerreduziert','Bio','Großpackung'], '1 Packung'],
  ['Haushalt', ['Toilettenpapier','Küchenrolle','Spülmittel','Spülmaschinentabs','Waschmittel','Weichspüler','Müllbeutel','Allzweckreiniger','Glasreiniger','Badreiniger','Schwämme','Backpapier','Alufolie','Frischhaltefolie','Gefrierbeutel'], ['klassisch','sensitiv','ökologisch','Nachfüllpack','Vorratspack'], '1 Packung'],
  ['Drogerie', ['Zahnpasta','Zahnbürsten','Duschgel','Shampoo','Spülung','Seife','Deodorant','Handcreme','Bodylotion','Taschentücher','Wattepads','Rasiergel','Rasierklingen','Sonnencreme','Pflaster'], ['klassisch','sensitiv','für Kinder','Naturkosmetik','Vorratspack'], '1 Packung'],
  ['Baby & Tierbedarf', ['Windeln','Feuchttücher','Babynahrung','Babybrei','Babyshampoo','Katzenfutter nass','Katzenfutter trocken','Katzenstreu','Hundefutter nass','Hundefutter trocken','Hundesnacks','Vogelfutter','Kleintierstreu','Tier-Spielzeug','Kotbeutel'], ['klassisch','sensitiv','Bio','Junior','Vorratspack'], '1 Packung'],
] as const;

const hygieneProducts: Product[] = [
  ['Mundspülung', 'Drogerie', '500 ml'],
  ['Zahnseide', 'Drogerie', '1 Packung'],
  ['Interdentalbürsten', 'Drogerie', '1 Packung'],
  ['Zungenreiniger', 'Drogerie', '1 Stück'],
  ['Zahnbürstenköpfe', 'Drogerie', '1 Packung'],
  ['Kinderzahnpasta', 'Drogerie', '1 Tube'],
  ['Flüssigseife', 'Drogerie', '1 Flasche'],
  ['Handseife Nachfüllpack', 'Drogerie', '1 Packung'],
  ['Duschcreme', 'Drogerie', '1 Flasche'],
  ['Duschöl', 'Drogerie', '1 Flasche'],
  ['Intimwaschlotion', 'Drogerie', '1 Flasche'],
  ['Trockenshampoo', 'Drogerie', '1 Dose'],
  ['Haarspülung', 'Drogerie', '1 Flasche'],
  ['Haarkur', 'Drogerie', '1 Packung'],
  ['Haarbürste', 'Drogerie', '1 Stück'],
  ['Kamm', 'Drogerie', '1 Stück'],
  ['Haargummis', 'Drogerie', '1 Packung'],
  ['Deospray', 'Drogerie', '1 Dose'],
  ['Deoroller', 'Drogerie', '1 Stück'],
  ['Gesichtsreinigung', 'Drogerie', '1 Flasche'],
  ['Gesichtswasser', 'Drogerie', '1 Flasche'],
  ['Gesichtscreme', 'Drogerie', '1 Tiegel'],
  ['Augencreme', 'Drogerie', '1 Tube'],
  ['Lippenpflege', 'Drogerie', '1 Stück'],
  ['Abschminktücher', 'Drogerie', '1 Packung'],
  ['Mizellenwasser', 'Drogerie', '400 ml'],
  ['Wattestäbchen', 'Drogerie', '1 Packung'],
  ['Kosmetiktücher', 'Drogerie', '1 Box'],
  ['Feuchtes Toilettenpapier', 'Drogerie', '1 Packung'],
  ['Waschlappen', 'Drogerie', '1 Stück'],
  ['Rasierschaum', 'Drogerie', '1 Dose'],
  ['Einwegrasierer', 'Drogerie', '1 Packung'],
  ['Aftershave', 'Drogerie', '1 Flasche'],
  ['Bartshampoo', 'Drogerie', '1 Flasche'],
  ['Bartöl', 'Drogerie', '1 Flasche'],
  ['Nagelschere', 'Drogerie', '1 Stück'],
  ['Nagelfeile', 'Drogerie', '1 Stück'],
  ['Nagelknipser', 'Drogerie', '1 Stück'],
  ['Handdesinfektionsmittel', 'Drogerie', '1 Flasche'],
  ['Desinfektionstücher', 'Drogerie', '1 Packung'],
  ['Wunddesinfektion', 'Drogerie', '1 Flasche'],
  ['Wundpflaster', 'Drogerie', '1 Packung'],
  ['Blasenpflaster', 'Drogerie', '1 Packung'],
  ['Mullbinden', 'Drogerie', '1 Packung'],
  ['Damenbinden', 'Drogerie', '1 Packung'],
  ['Tampons', 'Drogerie', '1 Packung'],
  ['Slipeinlagen', 'Drogerie', '1 Packung'],
  ['Menstruationstasse', 'Drogerie', '1 Stück'],
  ['Inkontinenzeinlagen', 'Drogerie', '1 Packung'],
  ['Kondome', 'Drogerie', '1 Packung'],
  ['Kontaktlinsenlösung', 'Drogerie', '1 Flasche'],
  ['Kontaktlinsenbehälter', 'Drogerie', '1 Stück'],
  ['Ohrenstöpsel', 'Drogerie', '1 Packung'],
  ['Sonnencreme Gesicht', 'Drogerie', '1 Tube'],
  ['Sonnencreme Kinder', 'Drogerie', '1 Flasche'],
  ['After-Sun-Lotion', 'Drogerie', '1 Flasche'],
  ['Insektenschutzspray', 'Drogerie', '1 Flasche'],
  ['Fußcreme', 'Drogerie', '1 Tube'],
  ['Hornhautfeile', 'Drogerie', '1 Stück'],
  ['Badezusatz', 'Drogerie', '1 Packung'],
  ['Badesalz', 'Drogerie', '1 Packung'],
  ['Bademantel', 'Drogerie', '1 Stück'],
  ['Mikrofaser-Handtuch', 'Drogerie', '1 Stück'],
  ['Reise-Hygieneset', 'Drogerie', '1 Set'],
  ['Hygienebeutel', 'Drogerie', '1 Packung'],
  ['Einmalhandschuhe', 'Drogerie', '1 Packung'],
  ['FFP2-Masken', 'Drogerie', '1 Packung'],
  ['Fieberthermometer', 'Drogerie', '1 Stück'],
  ['Läusekamm', 'Drogerie', '1 Stück'],
  ['Läuseshampoo', 'Drogerie', '1 Flasche'],
];

const additionalProductGroups = [
  ['Obst & Gemüse', '500 g', ['Aprikosen','Granatapfel','Grapefruit','Pomelo','Wassermelone','Honigmelone','Cantaloupe-Melone','Passionsfrucht','Maracuja','Papaya','Guave','Litschi','Kaki','Feigen','Datteln frisch','Johannisbeeren','Stachelbeeren','Brombeeren','Cranberrys','Holunderbeeren','Mirabellen','Quitten','Rhabarber','Kumquats','Physalis','Nashi-Birnen','Sternfrucht','Drachenfrucht','Kokosnuss','Kochbananen','Artischocken','Fenchel','Pak Choi','Mangold','Grünkohl','Wirsing','Rotkohl','Weißkohl','Spitzkohl','Rosenkohl','Chicorée','Endiviensalat','Eisbergsalat','Romanasalat','Frühlingszwiebeln','Schalotten','Pastinaken','Petersilienwurzel','Rote Bete','Steckrüben','Topinambur','Maiskolben','Okraschoten','Zuckerschoten','Grüne Bohnen','Dicke Bohnen','Kürbis Hokkaido','Butternut-Kürbis','Spargel grün','Spargel weiß']],
  ['Nudeln & Pasta', '500 g', ['Penne Rigate','Fusilli','Farfalle','Rigatoni','Tortiglioni','Maccheroni','Makkaroni','Linguine','Tagliatelle','Fettuccine','Pappardelle','Capellini','Bucatini','Vermicelli','Orecchiette','Conchiglie','Gnocchetti Sardi','Casarecce','Cavatappi','Radiatori','Ditalini','Risoni','Lasagneplatten','Cannelloni','Tortellini Käse','Tortellini Fleisch','Ravioli Ricotta-Spinat','Ravioli Fleisch','Spätzle','Knöpfle','Schupfnudeln','Maultaschen','Eiernudeln','Bandnudeln','Suppennudeln','Fadennudeln','Buchstabennudeln','Glasnudeln','Reisnudeln','Mie-Nudeln','Udon-Nudeln','Soba-Nudeln','Ramen-Nudeln','Vollkornspaghetti','Dinkelpasta','Linsennudeln','Kichererbsennudeln','Erbsennudeln','Maisnudeln','Glutenfreie Nudeln']],
  ['Sättigungsbeilagen', '500 g', ['Basmatireis','Jasminreis','Langkornreis','Rundkornreis','Risottoreis Arborio','Risottoreis Carnaroli','Milchreis','Wildreis','Naturreis','Vollkornreis','Parboiled Reis','Sushireis','Quinoa weiß','Quinoa rot','Quinoa tricolor','Hirse','Polenta','Buchweizen','Graupen','Perlgraupen','Amaranth','Dinkelreis','Ebly Zartweizen','Kartoffelknödel','Semmelknödel','Serviettenknödel','Gnocchi','Kartoffelpuffer','Rösti','Kartoffelgratin','Kartoffelecken','Süßkartoffelpommes','Kartoffelkroketten','Stampfkartoffeln','Couscous Vollkorn','Perlcouscous','Bulgur fein','Bulgur grob','Falafel-Mix','Baguette zum Aufbacken']],
  ['Fleisch & Geflügel', '500 g', ['Rinderhackfleisch','Gemischtes Hackfleisch','Schweinehackfleisch','Kalbshackfleisch','Rinderfilet','Rumpsteak','Entrecôte','Roastbeef','Rindergulasch','Rinderrouladen','Suppenfleisch','Tafelspitz','Kalbsschnitzel','Kalbsgulasch','Kalbsleber','Schweinefilet','Schweinekotelett','Schweinebauch','Schweinebraten','Schweinegulasch','Nackensteak','Kasseler','Spareribs','Lammfilet','Lammkotelett','Lammkeule','Lammhackfleisch','Wildgulasch','Rehkeule','Hirschsteak','Kaninchen','Hähnchen ganz','Hähnchenflügel','Hähnchenoberkeulen','Hähncheninnenfilet','Putensteak','Putenschnitzel','Entenbrust','Ente ganz','Gänsebrust','Gans ganz','Hähnchenleber','Rinderleber','Bacon','Frühstücksspeck','Chorizo','Mettenden','Leberkäse','Cevapcici','Frikadellen']],
  ['Grillen', '1 Packung', ['Grillbratwurst','Thüringer Rostbratwurst','Nürnberger Rostbratwürste','Krakauer','Käsekrainer','Merguez','Geflügelbratwurst','Vegane Grillwurst','Rinderhüftsteak mariniert','Schweinenacken mariniert','Holzfällersteak','Bauchscheiben mariniert','Spareribs mariniert','Hähnchenspieße','Putenspieße','Schaschlikspieße','Hackfleischspieße','Lammspieße','Grillfackeln','Burger Patties Rind','Burger Patties vegetarisch','Halloumi','Grillkäse','Feta zum Grillen','Maiskolben vorgekocht','Grillgemüse-Mix','Gefüllte Champignons','Folienkartoffeln','Kräuterbutter','Knoblauchbutter','Grillsauce BBQ','Steaksauce','Currysauce','Cocktailsauce','Knoblauchsauce','Chilisauce','Tzatziki','Senf mittelscharf','Ketchup','Mayonnaise','Burgerbrötchen Brioche','Hotdog-Brötchen','Baguette Kräuter','Kartoffelsalat','Nudelsalat','Krautsalat','Grillkohle','Grillbriketts','Anzündwürfel','Grillschalen','Grillspieße Holz','Aluminium-Grillfolie','Grillhandschuhe','Grillbürste','Räucherchips']],
  ['Backen & Kochen', '1 Packung', ['Weizenmehl Type 405','Weizenmehl Type 550','Weizenmehl Type 1050','Dinkelmehl Type 630','Dinkelmehl Type 1050','Roggenmehl Type 1150','Vollkornmehl','Pizzamehl Type 00','Speisestärke','Kartoffelstärke','Maisstärke','Paniermehl','Panko','Semmelbrösel','Trockenhefe','Frische Hefe','Natron','Weinsteinbackpulver','Vanillezucker','Bourbon-Vanillezucker','Puderzucker','Brauner Zucker','Rohrzucker','Gelierzucker 1:1','Gelierzucker 2:1','Gelierzucker 3:1','Kuvertüre Zartbitter','Kuvertüre Vollmilch','Kuvertüre weiß','Backkakao','Schokotropfen','Kokosraspeln','Gemahlene Mandeln','Gehackte Mandeln','Gemahlene Haselnüsse','Rosinen','Orangeat','Zitronat','Marzipanrohmasse','Tortenguss klar','Tortenguss rot','Sahnesteif','Gelatine gemahlen','Gelatineblätter','Agar-Agar','Puddingpulver Vanille','Puddingpulver Schokolade','Vanilleextrakt','Rum-Aroma','Bittermandel-Aroma','Zitronen-Aroma','Lebensmittelfarbe','Zuckerstreusel','Muffinförmchen','Backpapier Zuschnitte','Bratschlauch','Röstzwiebeln','Sojasauce','Worcestersauce','Balsamico-Essig','Apfelessig','Weißweinessig','Rotweinessig','Sesamöl','Rapsöl','Sonnenblumenöl','Erdnussöl','Butterschmalz','Kochsahne','Bratenfond','Rinderfond','Geflügelfond','Gemüsefond','Tomatensauce','Currypaste rot','Currypaste grün','Tahini','Erdnussbutter','Kapern','Oliven','Getrocknete Tomaten','Sambal Oelek','Meerrettich','Gewürzgurken','Senfkörner','Lorbeerblätter','Muskatnuss','Paprikapulver edelsüß','Paprikapulver geräuchert','Currypulver','Kreuzkümmel','Kurkuma','Zimt','Oregano','Thymian','Rosmarin','Basilikum getrocknet','Chiliflocken']],
] as const;

const additionalProducts: Product[] = additionalProductGroups.flatMap(([category, quantity, names]) =>
  names.map((name) => [name, category, quantity] as Product),
);

const spiceAndChilledProductGroups = [
  ['Gewürze & Kräuter', '1 Glas', ['Anis ganz','Sternanis','Bockshornklee gemahlen','Bohnenkraut','Cayennepfeffer','Chilifäden','Chilipulver','Dillspitzen','Estragon','Fenchelsamen','Galgant gemahlen','Gewürznelken','Ingwer gemahlen','Kardamom gemahlen','Kardamomkapseln','Kerbel','Koriander gemahlen','Koriandersamen','Kümmel ganz','Kümmel gemahlen','Liebstöckel','Majoran','Muskatblüte Macis','Nelken gemahlen','Piment ganz','Piment gemahlen','Safranfäden','Salbei','Schwarzkümmel','Senfpulver','Sumach','Wacholderbeeren','Zimtstangen','Zitronengras getrocknet','Zitronenpfeffer','Pfeffer schwarz ganz','Pfeffer schwarz gemahlen','Pfeffer weiß ganz','Pfeffer weiß gemahlen','Pfeffer grün','Rosa Pfefferbeeren','Szechuanpfeffer','Langer Pfeffer','Kubebenpfeffer','Rauchsalz','Meersalz grob','Fleur de Sel','Steinsalz','Selleriesalz','Knoblauchgranulat','Knoblauchpulver','Zwiebelgranulat','Zwiebelpulver','Petersilie getrocknet','Schnittlauch getrocknet','Minze getrocknet','Kräuter der Provence','Italienische Kräuter','Provenzalische Kräuter','Curryblätter','Kaffirlimettenblätter','Vanilleschoten','Vanille gemahlen','Tonka-Bohnen','Mohnsamen','Sesam weiß','Sesam schwarz','Leinsamen','Nigella-Samen'] ],
  ['Gewürzmischungen', '1 Dose', ['Ras el Hanout','Garam Masala','Tandoori Masala','Curry Madras','Curry mild','Curry scharf','Cajun-Gewürz','Chinese Five Spice','Za’atar','Harissa-Gewürz','Baharat','Gyros-Gewürz','Döner-Gewürz','Pizza-Gewürz','Pasta-Gewürz','Bratkartoffel-Gewürz','Pommes-Gewürz','Grillgewürz','Steakpfeffer','Hähnchen-Gewürz','Fisch-Gewürz','Wild-Gewürz','Gulasch-Gewürz','Hackfleisch-Gewürz','Kräuterbutter-Gewürz','Salatkräuter','Brotgewürz','Lebkuchengewürz','Spekulatiusgewürz','Pumpkin Spice','Chili-con-Carne-Gewürz','Paella-Gewürz','Taco-Gewürz','Fajita-Gewürz','Burrito-Gewürz','Guacamole-Gewürz','Kartoffel-Gewürz','Ofengemüse-Gewürz','Rührei-Gewürz','Quark-Gewürz','Tomaten-Mozzarella-Gewürz','Asia-Gewürz','Shawarma-Gewürz','Falafel-Gewürz','Pilz-Gewürz','Kebab-Gewürz','Pulled-Pork-Gewürz','Burger-Gewürz','BBQ-Rub rauchig','BBQ-Rub süß','Chimichurri-Gewürz'] ],
  ['Würzmittel & Saucen', '1 Flasche', ['Flüssigwürze','Flüssigrauch','Sriracha','Tabasco rot','Tabasco grün','Teriyakisauce','Hoisinsauce','Austernsauce','Fischsauce','Mirin','Reisessig','Ponzu-Sauce','Miso-Paste hell','Miso-Paste dunkel','Wasabi-Paste','Sojasauce hell','Sojasauce dunkel','Tamari','Ketjap Manis','Sweet-Chili-Sauce','Chili-Knoblauch-Sauce','Salsa Verde','Salsa Roja','Chipotle-Sauce','Jalapeño-Sauce','Trüffelsauce','Bratensauce','Jägersauce','Pfeffersauce','Rahmsauce','Sauce Hollandaise','Demi-glace','Gemüsebrühe Pulver','Rinderbrühe Pulver','Geflügelbrühe Pulver','Hühnerbrühe Würfel','Gemüsebrühe Würfel','Rinderbrühe Würfel'] ],
  ['Kühlregal – Molkerei', '1 Becher', ['Vollmilch 3,5 %','Fettarme Milch 1,5 %','ESL-Milch','Laktosefreie Milch','Frische Biomilch','Kondensmilch','Kaffeesahne','Schlagsahne','Kochsahne 15 %','Crème fraîche','Crème légère','Schmand','Saure Sahne','Buttermilch','Kefir natur','Ayran','Naturjoghurt 1,5 %','Naturjoghurt 3,5 %','Griechischer Joghurt','Joghurt mild','Vanillejoghurt','Erdbeerjoghurt','Kirschjoghurt','Pfirsichjoghurt','Heidelbeerjoghurt','Skyr natur','Skyr Vanille','Magerquark','Speisequark 20 %','Speisequark 40 %','Sahnequark','Kräuterquark','Frischkäse natur','Frischkäse Kräuter','Körniger Frischkäse','Mascarpone','Ricotta','Milchreis gekühlt','Grießpudding','Vanillepudding','Schokoladenpudding','Rote Grütze','Trinkjoghurt','Proteinpudding','Sprühsahne'] ],
  ['Kühlregal – Käse', '1 Packung', ['Gouda jung','Gouda mittelalt','Gouda alt','Edamer','Emmentaler','Tilsiter','Butterkäse','Maasdamer','Bergkäse','Cheddar mild','Cheddar gereift','Gruyère','Appenzeller','Comté','Brie','Camembert','Gorgonzola','Roquefort','Ziegenkäserolle','Ziegenfrischkäse','Schafskäse','Feta','Halloumi','Mozzarella','Büffelmozzarella','Burrata','Parmesan am Stück','Grana Padano','Pecorino','Harzer Käse','Raclettekäse','Ofenkäse','Scheibenkäse Gouda','Scheibenkäse Emmentaler','Reibekäse Mozzarella','Reibekäse Gratinkäse','Schmelzkäse Scheiben','Mini-Käse-Snacks'] ],
  ['Kühlregal – Aufschnitt', '1 Packung', ['Kochschinken','Lachsschinken','Serrano-Schinken','Parmaschinken','Schwarzwälder Schinken','Putenbrust-Aufschnitt','Hähnchenbrust-Aufschnitt','Roastbeef-Aufschnitt','Mortadella','Lyoner','Jagdwurst','Fleischwurst','Bierschinken','Salami fein','Salami grob','Fenchelsalami','Chorizo-Aufschnitt','Teewurst fein','Teewurst grob','Leberwurst fein','Kalbsleberwurst','Mettwurst','Zwiebelmettwurst','Corned Beef','Aspik-Aufschnitt','Vegetarischer Aufschnitt','Veganer Aufschnitt'] ],
  ['Kühlregal – Feinkost', '1 Packung', ['Hummus natur','Hummus Paprika','Guacamole','Tzatziki','Aioli','Kräuterbutter gekühlt','Knoblauchbutter gekühlt','Fleischsalat','Eiersalat','Geflügelsalat','Heringssalat','Krabbensalat','Kartoffelsalat mit Mayonnaise','Kartoffelsalat mit Essig und Öl','Nudelsalat','Krautsalat','Coleslaw','Farmersalat','Waldorfsalat','Antipasti-Mix','Gegrillte Paprika','Eingelegte Artischocken','Oliven-Mix','Pesto Genovese frisch','Pesto Rosso frisch','Salsa Dip frisch','Frische Suppe Tomate','Frische Suppe Kürbis','Frische Suppe Kartoffel','Frische Brühe','Heringsfilet in Sahnesauce','Matjesfilets','Räucherlachs','Graved Lachs','Forellenfilet geräuchert'] ],
  ['Kühlregal – Teige & Frischpasta', '1 Packung', ['Pizzateig frisch','Blätterteig frisch','Flammkuchenteig','Quicheteig','Croissantteig','Brötchenteig','Knack-und-Back-Brötchen','Frische Spaghetti','Frische Tagliatelle','Frische Linguine','Frische Gnocchi','Frische Schupfnudeln','Frische Spätzle','Tortellini Ricotta-Spinat frisch','Tortellini Käse frisch','Tortellini Fleisch frisch','Ravioli Steinpilz frisch','Ravioli Ricotta-Spinat frisch','Maultaschen klassisch','Maultaschen vegetarisch','Klöße halb und halb gekühlt','Kartoffelknödelteig','Serviettenknödel gekühlt'] ],
  ['Kühlregal – Fertiggerichte', '1 Packung', ['Frische Pizza Margherita','Frische Pizza Salami','Frische Pizza Schinken','Lasagne Bolognese gekühlt','Lasagne Gemüse gekühlt','Cannelloni gekühlt','Tortellini-Auflauf','Nudelauflauf','Kartoffelgratin gekühlt','Käsespätzle gekühlt','Schupfnudelpfanne','Gebratene Nudeln gekühlt','Fertiger Pizzateig mit Sauce','Frikadellen gegart','Mini-Frikadellen','Schnitzel gegart','Cordon bleu gekühlt','Hähnchenschnitzel gegart','Bratkartoffeln gekühlt','Kartoffelpüree gekühlt','Semmelknödel gegart','Reibekuchenteig','Germknödel gekühlt'] ],
  ['Kühlregal – Pflanzlich', '1 Packung', ['Naturtofu','Räuchertofu','Tofu Kräuter','Tofu mediterran','Seidentofu','Tempeh natur','Tempeh mariniert','Seitan natur','Veganes Hack gekühlt','Vegane Burger-Patties','Vegane Bratwurst gekühlt','Veganes Schnitzel','Vegane Nuggets','Vegane Frikadellen','Vegane Maultaschen','Veganer Feta-Ersatz','Veganer Reibekäse','Veganer Scheibenkäse','Veganer Frischkäse','Haferjoghurt natur','Sojajoghurt natur','Sojajoghurt Vanille','Kokosjoghurt','Mandeljoghurt','Hafer Cuisine','Soja Cuisine','Vegane Schlagcreme'] ],
] as const;

const spiceAndChilledProducts: Product[] = spiceAndChilledProductGroups.flatMap(([category, quantity, names]) =>
  names.map((name) => [name, category, quantity] as Product),
);

export const extendedCatalog: Product[] = [
  ...groups.flatMap(([category, bases, variants, quantity]) =>
    bases.flatMap((base) => variants.map((variant) => [`${base} – ${variant}`, category, quantity] as Product)),
  ).slice(0, 850),
  ...hygieneProducts,
  ...additionalProducts,
  ...spiceAndChilledProducts,
];
